# Data Manipulation with NumPy and Pandas

> Now that we had a chance to start learning the basics of NumPy and Pandas, let's combine the two together and begin to learn how to use these packages for a simple data analysis.

### Let's have a look at the top  3 things that we need to know about NumPy and Pandas


<img src="data/images/numpy_pandas.png" style="width: 400px">

<div class="alert alert-block alert-info">
<b>#1:</b> The data manipulation capabilities of pandas are built on top of the numpy library. In a way, numpy is a dependency of the pandas library.
</div>

<div class="alert alert-block alert-info">
<b>#2:</b> 
Pandas is best at handling tabular data sets comprising different variable types (integer, float, double, etc.). In addition, the pandas library can also be used to load data or do feature engineering on time series data.
</div>

<div class="alert alert-block alert-info">
<b>#3:</b> Numpy is most suitable for performing basic numerical computations such as mean, median, range, etc. Alongside, it also supports the creation of multi-dimensional arrays (as we already know it ¯\_(ツ)_/¯).
</div>

# Re-cap exercises

- Let's practice and re-cap on our NumPy and Pandas skills
- We are going to use a few adopted examples from different online sources


In [1]:
import numpy as np

In [2]:
#converting integers to string - this style of handling lists is known as list comprehension.

L = list(range(10))
[str(c) for c in L]

# [type(item) for item in L]
# [int, int, int, int, int, int, int, int, int, int]

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [3]:
#creating arrays
np.zeros(10, dtype='int')


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
#creating a matrix with a predefined value
np.full((3,5),5.45)

array([[5.45, 5.45, 5.45, 5.45, 5.45],
       [5.45, 5.45, 5.45, 5.45, 5.45],
       [5.45, 5.45, 5.45, 5.45, 5.45]])

In [5]:
#create an array of even space between the given range of values
np.linspace(0, 2, 5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [6]:

#create a 3x3 array with mean 0 and standard deviation 1 in a given dimension
np.random.normal(0, 1, (3,3))

array([[-0.07905857, -0.75633078,  0.89325033],
       [ 1.45352522,  0.49020399, -0.86414331],
       [-0.03028346,  0.7328823 , -0.08663388]])

In [7]:
# Concatenating arrays

x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = [21,21,21]
np.concatenate([x, y,z])

array([ 1,  2,  3,  3,  2,  1, 21, 21, 21])

In [8]:
# We can create 2-dimensional arrays.
grid = np.array([[1,2,3],[4,5,6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

> Until now, we used the concatenation function of arrays of equal dimension. But, what if you are required to combine a 2D array with 1D array? In such situations, np.concatenate might not be the best option to use. Instead, you can use np.vstack or np.hstack to do the task. 

In [10]:
x = np.array([3,4,5])
grid = np.array([[1,2,3],[17,18,19]])
np.vstack([x,grid])

array([[ 3,  4,  5],
       [ 1,  2,  3],
       [17, 18, 19]])

In [11]:
z = np.array([[9],[9]])
np.hstack([grid,z])

array([[ 1,  2,  3,  9],
       [17, 18, 19,  9]])

# Let's start analysing

- we are going to use Pandas and later NumPy to learn new techniques to perform data analysis
- Let's code together

In [12]:
import pandas as pd

In [13]:
#create a data frame - dictionary is used here where keys get converted to column names and values to row values.

data = pd.DataFrame({'Fruit': ['Peach','Apple','Pear','Plum','Kiwi'],
                    'Items':[121,40,100,130,11]})
data

Fruit  Items
0  Peach    121
1  Apple     40
2   Pear    100
3   Plum    130
4   Kiwi     11

In [14]:
#We can do a quick analysis of any data set using:
data.describe()

Items
count    5.000000
mean    80.400000
std     52.300096
min     11.000000
25%     40.000000
50%    100.000000
75%    121.000000
max    130.000000

In [15]:
# To get the complete information about the data set, we can use info() function.
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Fruit   5 non-null      object
 1   Items   5 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 208.0+ bytes


In [16]:
#Let's create another data frame.

data = pd.DataFrame({'group':['a', 'a', 'a', 'b','b', 'b', 'c', 'c','c'],'kg':[4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

group    kg
0     a   4.0
1     a   3.0
2     a  12.0
3     b   6.0
4     b   7.5
5     b   8.0
6     c   3.0
7     c   5.0
8     c   6.0

In [17]:
#Let's sort the data frame by kg - inplace = True will make changes to the data
data.sort_values(by=['kg'],ascending=True,inplace=False)

group    kg
1     a   3.0
6     c   3.0
0     a   4.0
7     c   5.0
3     b   6.0
8     c   6.0
4     b   7.5
5     b   8.0
2     a  12.0

In [18]:
# sort by multiple columns

data.sort_values(by=['group','kg'],ascending=[True,False],inplace=False)

group    kg
2     a  12.0
0     a   4.0
1     a   3.0
5     b   8.0
4     b   7.5
3     b   6.0
8     c   6.0
7     c   5.0
6     c   3.0

In [19]:
#create another data with duplicated rows

data = pd.DataFrame({'names':['Mila']*3 + ['Igor']*4, 'Age':[3,2,1,3,3,4,4]})
data

names  Age
0  Mila    3
1  Mila    2
2  Mila    1
3  Igor    3
4  Igor    3
5  Igor    4
6  Igor    4

In [20]:
#remove duplicates - ta da! 
data.drop_duplicates()

names  Age
0  Mila    3
1  Mila    2
2  Mila    1
3  Igor    3
5  Igor    4

In [21]:
# Alternatively, we can also remove duplicates based on a particular column. 
# Let's remove duplicate values from the name column.

data.drop_duplicates(subset='names')


names  Age
0  Mila    3
3  Igor    3

# Farm Shop Exercise

- Let's do some data manipulation for a lovely farm shop
- We are going to build a data set and do some simple manipulation to make it better
- We will learn to categorize rows based on a predefined criteria. 
- It happens a lot in data processing where you need to categorize a variable. 
- For example, say we have got a column with animals and we want to create a new variable 'animal kingdom' based on these animal names.


<img src="/Users/fernandes/Desktop/Data_Stream/data/images/farm.jpg" style="width: 400px">

In [22]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Jerky beef','corned beef', 'Bacon', 'jerky beef', 'ham','lox'],
                 'kg': [4, 3, 11, 5.6, 7.5, 8, 3, 5, 6]})
data

food    kg
0        bacon   4.0
1  pulled pork   3.0
2        bacon  11.0
3   Jerky beef   5.6
4  corned beef   7.5
5        Bacon   8.0
6   jerky beef   3.0
7          ham   5.0
8          lox   6.0

In [23]:
"""
We want to create a new variable which maps the type of animal to the source of food. 
First we'll create a dictionary to map the food to the animals. 
Then, we'll use map function to map the dictionary's values to the keys. 
"""

meat_to_animal = {
'bacon': 'pig',
'pulled pork': 'pig',
'jerky beef': 'cow',
'corned beef': 'cow',
'ham': 'pig',
'lox': 'salmon'
}

def meat_2_animal(series):
    if series['food'] == 'bacon':
        return 'pig'
    elif series['food'] == 'pulled pork':
        return 'pig'
    elif series['food'] == 'jerky beef':
        return 'cow'
    elif series['food'] == 'corned beef':
        return 'cow'
    elif series['food'] == 'ham':
        return 'pig'
    else:
        return 'salmon'


#create a new variable
data['animal'] = data['food'].map(str.lower).map(meat_to_animal)
data

food    kg  animal
0        bacon   4.0     pig
1  pulled pork   3.0     pig
2        bacon  11.0     pig
3   Jerky beef   5.6     cow
4  corned beef   7.5     cow
5        Bacon   8.0     pig
6   jerky beef   3.0     cow
7          ham   5.0     pig
8          lox   6.0  salmon

In [24]:
"""
This is another way of doing it is: convert the food values to the lower case and apply the function
Lambda is an anonymous function, which is represents functional programming (instead of OOO) in Python
Lambda does not need to be specifically defined and can be applied to values dynamically.
"""

lower = lambda x: x.lower()
data['food'] = data['food'].apply(lower)
data['animal2'] = data.apply(meat_2_animal, axis='columns')
data

food    kg  animal animal2
0        bacon   4.0     pig     pig
1  pulled pork   3.0     pig     pig
2        bacon  11.0     pig     pig
3   jerky beef   5.6     cow     cow
4  corned beef   7.5     cow     cow
5        bacon   8.0     pig     pig
6   jerky beef   3.0     cow     cow
7          ham   5.0     pig     pig
8          lox   6.0  salmon  salmon

In [25]:
"""
Another way to create a new variable is by using the assign function. 
It is another very powerful feature in Pandas.
"""

data.assign(new_variable = data['kg']*10)

food    kg  animal animal2  new_variable
0        bacon   4.0     pig     pig          40.0
1  pulled pork   3.0     pig     pig          30.0
2        bacon  11.0     pig     pig         110.0
3   jerky beef   5.6     cow     cow          56.0
4  corned beef   7.5     cow     cow          75.0
5        bacon   8.0     pig     pig          80.0
6   jerky beef   3.0     cow     cow          30.0
7          ham   5.0     pig     pig          50.0
8          lox   6.0  salmon  salmon          60.0

In [26]:
"""
Let's remove animal2 from our data set
We don't really need that column
"""

data.drop('animal2',axis='columns',inplace=True)
data

food    kg  animal
0        bacon   4.0     pig
1  pulled pork   3.0     pig
2        bacon  11.0     pig
3   jerky beef   5.6     cow
4  corned beef   7.5     cow
5        bacon   8.0     pig
6   jerky beef   3.0     cow
7          ham   5.0     pig
8          lox   6.0  salmon

# Categorization

- Now let's learn how to rename data sets or columns
- We also will learn how to categorize our data 


<img src="data/images/categorize.jpg" style="width: 400px">

In [26]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),index=['London', 'Manchester', 'Brighton'],columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
London        0    1      2     3
Manchester    4    5      6     7
Brighton      8    9     10    11

In [27]:
# let's learn how to rename column names and axis (row names).
data.rename(index = {'Manchester':'Cardiff'}, columns={'one':'one_p','two':'two_p'},inplace=True)
data

one_p  two_p  three  four
London        0      1      2     3
Cardiff       4      5      6     7
Brighton      8      9     10    11

In [28]:
# Using string functions

data.rename(index = str.upper, columns=str.title,inplace=True)
data

One_P  Two_P  Three  Four
LONDON        0      1      2     3
CARDIFF       4      5      6     7
BRIGHTON      8      9     10    11

In [29]:
"""
Now let's lsee how to categorize (bin) continuous variables.
We have a variable ages.
We'll divide the ages into bins (categories) such as 18-25, 26-35,36-60 and 60 and above.
"""

ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [30]:
bins = [18, 25, 35, 60, 100]
categories = pd.cut(ages, bins)
categories

# IMPORTANT: look at the output - ']' indicates whether bins includes the rightmost edge or not (it is included by default).
# You can read more about bins and edges in the docs: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.cut.html 

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [31]:
#To include the right bin value, we can do:
pd.cut(ages,bins,right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [32]:
# See  how many observations fall under each bin
pd.value_counts(categories)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [33]:
# Add unique name to each category

bin_names = ['Youth', 'Early 20s', 'Middle Age', 'Senior']
new_cats = pd.cut(ages, bins,labels=bin_names)

pd.value_counts(new_cats)

Youth         5
Middle Age    3
Early 20s     3
Senior        1
dtype: int64

# Analyzing Data Set and its Shape

<img src="data/images/shapes.png" style="width: 500px">

In [34]:
# Slicing Data Frame

dates = pd.date_range('20210701',periods=7)
df = pd.DataFrame(np.random.randn(7,4),index=dates,columns=list('ABCD'))
df

A         B         C         D
2021-07-01 -0.142647 -0.545968  0.590888  0.743643
2021-07-02 -1.150522  0.695551 -1.282184  0.550813
2021-07-03  0.815886  1.293731 -1.760001  0.469452
2021-07-04  1.638121 -0.965062 -1.135230  2.336153
2021-07-05  1.718498 -0.709034  1.528670  0.237281
2021-07-06 -1.121405 -1.266788 -0.575361 -0.752205
2021-07-07 -1.210077 -0.803122  0.611150  1.539554

In [35]:
#get first n rows from the data frame
df[:3]

A         B         C         D
2021-07-01 -0.142647 -0.545968  0.590888  0.743643
2021-07-02 -1.150522  0.695551 -1.282184  0.550813
2021-07-03  0.815886  1.293731 -1.760001  0.469452

In [36]:
#slice based on date range
df['20210701':'20210705']

A         B         C         D
2021-07-01 -0.142647 -0.545968  0.590888  0.743643
2021-07-02 -1.150522  0.695551 -1.282184  0.550813
2021-07-03  0.815886  1.293731 -1.760001  0.469452
2021-07-04  1.638121 -0.965062 -1.135230  2.336153
2021-07-05  1.718498 -0.709034  1.528670  0.237281

In [37]:
#slicing based on column names
df.loc[:,['A','B']]

A         B
2021-07-01 -0.142647 -0.545968
2021-07-02 -1.150522  0.695551
2021-07-03  0.815886  1.293731
2021-07-04  1.638121 -0.965062
2021-07-05  1.718498 -0.709034
2021-07-06 -1.121405 -1.266788
2021-07-07 -1.210077 -0.803122

In [38]:
#slicing based on both row index labels and column names
df.loc['20210701':'20210705',['A','B']]

A         B
2021-07-01 -0.142647 -0.545968
2021-07-02 -1.150522  0.695551
2021-07-03  0.815886  1.293731
2021-07-04  1.638121 -0.965062
2021-07-05  1.718498 -0.709034

In [39]:
#slicing based on index of columns

df.iloc[2] #returns 3rd row (index is 2nd)


A    0.815886
B    1.293731
C   -1.760001
D    0.469452
Name: 2021-07-03 00:00:00, dtype: float64

In [40]:
#returns a specific range of rows
df.iloc[2:4, 0:2]

A         B
2021-07-03  0.815886  1.293731
2021-07-04  1.638121 -0.965062

In [41]:
#returns specific rows and columns using lists containing columns or row indexes
df.iloc[[1,5],[0,2]] 

A         C
2021-07-02 -1.150522 -1.282184
2021-07-06 -1.121405 -0.575361

In [42]:
#we can copy the data set
df2 = df.copy()
df2['E']=['one', 'one','two','three','four','three','two']
df2

A         B         C         D      E
2021-07-01 -0.142647 -0.545968  0.590888  0.743643    one
2021-07-02 -1.150522  0.695551 -1.282184  0.550813    one
2021-07-03  0.815886  1.293731 -1.760001  0.469452    two
2021-07-04  1.638121 -0.965062 -1.135230  2.336153  three
2021-07-05  1.718498 -0.709034  1.528670  0.237281   four
2021-07-06 -1.121405 -1.266788 -0.575361 -0.752205  three
2021-07-07 -1.210077 -0.803122  0.611150  1.539554    two

In [43]:
#select rows based on column values
df2[df2['E'].isin(['two','four'])]

A         B         C         D     E
2021-07-03  0.815886  1.293731 -1.760001  0.469452   two
2021-07-05  1.718498 -0.709034  1.528670  0.237281  four
2021-07-07 -1.210077 -0.803122  0.611150  1.539554   two

In [44]:
#select all rows except those with two and four
df2[~df2['E'].isin(['two','four'])]

A         B         C         D      E
2021-07-01 -0.142647 -0.545968  0.590888  0.743643    one
2021-07-02 -1.150522  0.695551 -1.282184  0.550813    one
2021-07-04  1.638121 -0.965062 -1.135230  2.336153  three
2021-07-06 -1.121405 -1.266788 -0.575361 -0.752205  three

In [45]:
#list all columns where B is greater than D
df.query('B > D')

A         B         C         D
2021-07-02 -1.150522  0.695551 -1.282184  0.550813
2021-07-03  0.815886  1.293731 -1.760001  0.469452

# Pivoting Data

- Learn about creating pivots in pandas. 
- It's a VERY important data analysis method which you re likely to use on majority of datasets in the future
- Pivot tables are extremely useful in analyzing data using a customized tabular format. 


<img src="data/images/workflow.png" style="width: 500px">

In [46]:
# new a data frame

data = pd.DataFrame({'group': ['x', 'x', 'x', 'y','y', 'y', 'z', 'z','z'],
                 'kg': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

group    kg
0     x   4.0
1     x   3.0
2     x  12.0
3     y   6.0
4     y   7.5
5     y   8.0
6     z   3.0
7     z   5.0
8     z   6.0

In [47]:
#calculate mean for each group
data.pivot_table(
    values='kg',
    index='group',
    aggfunc=np.mean
)

kg
group          
x      6.333333
y      7.166667
z      4.666667

In [48]:
#calculate count by each group
data.pivot_table(
    values='kg',
    index='group',
    aggfunc='count'
)

kg
group    
x       3
y       3
z       3

# Intersection analytics example (advanced)

### How to get the items not common to both series A and series B ?

In [49]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

# get union of two series
union = pd.Series(np.union1d(ser1, ser2))

# intersect two series
intersect = pd.Series(np.intersect1d(ser1, ser2))  

# project values from union, which do not appear in the intersection
union[~union.isin(intersect)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

# Most used operation

### How to convert a numpy array to a dataframe of given shape? 

In [50]:
# Reshape the series into a dataframe with 8 rows and 5 columns
ser = pd.Series(np.random.randint(1, 10, 40))
df = pd.DataFrame(ser.values.reshape(8,5))

print(df)

   0  1  2  3  4
0  3  8  3  8  1
1  6  6  2  9  4
2  4  6  6  5  9
3  4  4  4  1  6
4  6  7  2  8  7
5  2  1  3  1  9
6  5  2  6  2  5
7  3  6  3  6  6
